FROM php:7.2-fpm
MAINTAINER Bruno Perel

RUN apt-get update && apt-get install -y git unzip zlib1g-dev

RUN docker-php-ext-install -j$(nproc) mbstring zip

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN pecl install xdebug-2.6.1 && docker-php-ext-enable xdebug
RUN echo "xdebug.remote_enable = 1" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini